### ISSUE TITLE
Custom tag doesn`t render

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [ellmetha/django-precise-bbcode#10]
![issue](https://cloud.githubusercontent.com/assets/16137770/12718516/1a4fd006-c900-11e5-87a2-b08fb258d2ee.png)
Custom tag renders when it's content contains one line, but when it's content contains more, than one line it doesn't render. If I turn 'End tag closing' off, it renders, but it contains one line in html. 
P.S. Sorry for my English.

**Comment by ellmetha** [comment]
Hi,
Could you copy paste the definition of your BBCode tag (BBCode definition and HTML replacement code)?

**Comment by Valeriy-Zainullin** [comment]
Tag definition: `[src={CHOICE=Python,Bash,Ruby,JavaScript,HTML,CSS3,C++,C,Java,C#,Scala}]{TEXT}[/src]`
Replacement HTML code: `<span class="code-{CHOICE=Python,Bash,Ruby,JavaScript,HTML,CSS3,C++,C,Java,C#,Scala}">{TEXT}</span>`

**Comment by ellmetha** [comment]
Thanks for reporting this.
I will release a new version of *django-precise-bbcode* that includes this bugfix soon. ;)
