### ISSUE TITLE
core.loading fails to load modules new style Django Apps

### ISSUE THREAD

**Issue by whs** [ellmetha/django-precise-bbcode#14]
Django since 1.7 now [supports](https://docs.djangoproject.com/en/1.7/ref/applications/) listing the application's config class in `INSTALLED_APPS` instead of module name.

This breaks [core.loading.load](https://github.com/ellmetha/django-precise-bbcode/blob/develop/precise_bbcode/core/loading.py), as it expect everything to be module names.

**Comment by ellmetha** [comment]
Thanks for reporting this! This has been fixed in cbbf2b4. I should release a new version of *django-precise-bbcode* including this fix soon. :wink:
