### ISSUE TITLE
Smiley Link not working.

### ISSUE THREAD

**Issue by TheDocter** [ellmetha/django-precise-bbcode#20]
I have added a smiley via the django admin area. THe issue is when I add it to my site using the code i created it does not show up. It cant even find it. I can find it on the local machine uploaded to the directory but it won't render on screen.

![issuewithsmilies](https://user-images.githubusercontent.com/7916691/41615661-1564fe20-73b9-11e8-9cac-c60ce236a871.png)

![being rendered](https://user-images.githubusercontent.com/7916691/41615782-65494716-73b9-11e8-8f3a-1cc31f5dfa7f.png)

As you can see it was uploaded to the project folder. But it wont load..
![inprojectfolder](https://user-images.githubusercontent.com/7916691/41615915-cf939c34-73b9-11e8-9a47-6b2a1c1f8e9a.png)

**Comment by ellmetha** [comment]
I believe this is related to a problem in the way your project is configured. Check your media configuration 😉

**Comment by ellmetha** [comment]
Closing since this is not really related to the project itself.

**Comment by ViennaSand** [comment]
Dear ellmetha,
I wish you would be a bit more specific. I am undergoing the exact same problem and I have no clue what "check your media configuration" means. It would be helpful in your documentation to specify what we need to do in the install process not to undergo this problem. 
Also, I wish I had more specific guidelines on how to have the buttons of the bbcode (just like here on github) in the admin area to enter the content of a blog post on top of the text area.
It may not be directly related to the project, but it is directly linked to the "getting started" doc.
Kind regards

**Comment by TheDocter** [comment]
The media settings are not part of the project. I forgot to set my media root and media url inside the settings.py. The following is what fixed my issue.

`# Media Root
MEDIA_ROOT = os.path.join(PROJECT_PATH, 'media')
MEDIA_URL = '/media/'`

Make sure you edit root to fit your project needs.

**Comment by TheDocter** [comment]
Also as far as the editor ellmetha mentions it will not be part of this project in another issue located here

https://github.com/ellmetha/django-precise-bbcode/issues/13

**Comment by ViennaSand** [comment]
Thank you very very much for your prompt answer.
At the moment I copied/paste in the following way,
> MEDIA_ROOT = os.path.join(PROJECT_PATH, ’smilies') MEDIA_URL = ‘/my_app/'
> 
But it still does not work.
The error I get is that I requested URL http://127.0.0.1:8000/my_app/precise_bbcode/smilies/my_smiley.gif <http://127.0.0.1:8000/my_app/precise_bbcode/smilies/my_smiley.gif>

It shows that it tried the URLS patterns which show the path to my file but it is not looking for my file but for the index page instead.
I don’t understand what I’ve done wrong.

**Comment by TheDocter** [comment]
Again you cant just copy and past. My MEDIA_ROOT has PROJECT_PATH which is a custom variable i have created in my settings.py file. You will need to set up media_root to fit your profiles.

**Comment by ViennaSand** [comment]
Thanks a lot with your hints, I could finally understand what I was missing:
once the MEDIA_ROOT and MEDIA_URL are setup in the settings.py

You have to go to urls.py and add the following:
from django.conf.urls.static import static
from my_project import settings (assuming that the MEDIA_ROOT is the my_porject folder)
 
and then url patterns =[
    #whatever
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

With this correction, when I upload the smiley in the admin page, I have access to my smiley, at last.
Now, I can focus on the rendering.

All the best!

**Comment by TheDocter** [comment]
Oh yea. I forgot about the urls.py file. Sorry about that.

**Comment by ViennaSand** [comment]
No worries, it is also good to do part of the way in an autonomous way ;-) You've been so helpful! Thanks again
