### ISSUE TITLE
Documentation mislabels "BBCODE_SMILIES_UPLOAD_TO" as "SMILIES_UPLOAD_TO"

### ISSUE THREAD

**Issue by melchior-4** [ellmetha/django-precise-bbcode#22]
On the settings page under Smilies, the setting for the media subdirectory where smilies are uploaded to is presented as "SMILIES_UPLOAD_TO" instead of "BBCODE_SMILIES_UPLOAD_TO"

**Comment by ellmetha** [comment]
Thanks for reporting this!
