### ISSUE TITLE
A BBCode tag with this name appears to already exist

### ISSUE THREAD

**Issue by fuuwah** [ellmetha/django-precise-bbcode#3]
When editing a custom tag in the admin I get the error "A BBCode tag with this name appears to already exist" after saving. Renaming the tag to something else fixes the issue, but deleting the tag and recreating it still gives the same error. This makes any tag names savable only once.

I am running latest master branch bf889d8c6b6b94b63c0b73c72b6122fc717feb24 on python 2.7 and django 1.7.

**Comment by ellmetha** [comment]
Hi,

Thanks for checking in, and reporting this issue!
I just fixed it. You can upgrade your version of *django-precise-bbocde* with pip to get the latest version. ;)

``pip install django-precise-bbcode==1.0.1``

**Comment by fuuwah** [comment]
Sorry for my late reply. Editing now works, but deleting the tag still makes it non-reusable for later.

Example, create:
```
[test]{URL}[/test]
<test>{URL}</test>
```

Editing now works in 1.0.1:
```
[test]{URL}[/test]
<test src='{URL}'>
```

Delete the "test" tag in the admin. It's impossible to recreate a "test" tag later on.

**Comment by ellmetha** [comment]
OK, thanks for reporting again.
There must be a problem with the pool of BBCode tags. Tags seems to not be deleted from it when they are actually removed from the database.
I will dig in further and come up with a fix for this soon. ;)

**Comment by ellmetha** [comment]
The problem is resolved.
Please upgrade your version of *django-precise-bbcode* to get the latest version (``1.0.2``).
