### ISSUE TITLE
A BBCode tag with this name appears to already exist

### ISSUE THREAD

**Issue by Vorlif** [ellmetha/django-precise-bbcode#4]
Hey guys,

i have the same error how [here](https://github.com/ellmetha/django-precise-bbcode/issues/3) with the current version (1.0.8) and Django 1.8. I can create a Custom BBcode. After delete of this, i can not create a new BBcode with the same Tag. A restart of Django solve this error.

Is this a Issue or a failure on my site?

Thx

**Comment by ellmetha** [comment]
I think you were using the admin's bulk delete feature. This feature does not call the ``delete()`` method on model instances. This is why a  ``ValidationError`` was raised.
