### ISSUE TITLE
add admin editor

### ISSUE THREAD

**Issue by perthvader** [ellmetha/django-precise-bbcode#5]
It would be nice to have something like [wysibb.com](http://www.wysibb.com) in the django-admin

**Comment by ellmetha** [comment]
Hi!

Thanks for your comment.
For now I do no want to tie *django-precise-bbcode* with a specific bbcode editor like wysibb. A 'contrib' module could eventually be written to support this library. But this implies that BBCode tags defined with *django-precise-bbocde* should be used in the initialization of the editor. The BBCode tags provided by *django-precise-bbcode* should exactly match the ones provided by this library.

I do not plan to add this kind of "widgets" to the module right now. But feel free to contribute. ;)
