### ISSUE TITLE
Django 1.9 warning

### ISSUE THREAD

**Issue by sergei-maertens** [ellmetha/django-precise-bbcode#6]
In Django 1.9 django.db.models.get_model is removed in favour of the AppConfig (app.get_model(...)). On Django 1.8 the following warning is now spit out:

    /path/to/venv/lib/python2.7/site-packages/precise_bbcode/bbcode/__init__.py:115:     RemovedInDjango19Warning: django.db.models.get_model is deprecated.
      SmileyTag = get_model('precise_bbcode', 'SmileyTag')

**Comment by ellmetha** [comment]
Hi!

Thanks for checking in, and reporting this issue!
I will add a patch for this soon. ;)
