### ISSUE TITLE
BBcode converted into text

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [ellmetha/django-precise-bbcode#8]
![2](https://cloud.githubusercontent.com/assets/16137770/12701244/6ef90786-c814-11e5-80ac-c86fb3c40fb3.png) BBcode simply converts into text in html.

**Comment by ellmetha** [comment]
Hi,
How are you displaying your BBCode content in your templates? Are you using the latest version of *django-precise-bbcode*? Do you use the ``safe`` filter tag when trying to display your bbcode contents in your templates?

**Comment by Valeriy-Zainullin** [comment]
I've installed latest version through pip. I use |escape in my template's variables to prevent html tags. I chose bbcode as safe variant of html. When I remove escape from variables nothing happens. It renders just like in the first post.

**Comment by ellmetha** [comment]
Can you copy paste the relevant part of your template where you are displaying your BBCode tags ?

**Comment by Valeriy-Zainullin** [comment]
`{% extends 'main.html' %}
{% load mptt_tags %}
{% load bbcode_tags %}
{% bbcode entry.bbcode_content %}
{% block 'keywords' %}{% for item in Post.tags.all %},{{item}}{% endfor %}{% endblock %}
{% block 'content' %}
   <div class="Post-overview" id="{{Post.id}}">
       <div class="Post-overview-image"><img src="{{Post.image.url}}" height="128" width="128"></div>
       <div class="text">
           <div><span class="Post-overview-title">{{Post.title|escape}}</span></div>
           <div><span class="Post-overview-created">{{Post.created_at}}</span></div>
           <div><span class="Post-overview-description">{{Post.description|escape}}</span></div>
           <div><span class="Post-overview-tags">Теги: &nbsp;&nbsp;{% for item in Post.tags.all %}<a href="/?tags={{item.tag}}">{{item.tag|escape}}</a>{% endfor %}</span></div>
       </div>
   </div>
   <div class="Post-body">{{Post.body|escape|bbcode}}</div>
   <div class="Post-comments">
       {% if Post.comments.all %}<small style='text-align: right;'>Комментарии: {{Post.comments.all|length}}</small>{% endif %}
       {% if request.user.is_authenticated %}
           <form action="{% url 'comment_add' %}" method="POST" enctype="application/x-www-form-urlencoded">
           {% csrf_token %}
           <span id="comment-add-parent"></span>
           <input type="hidden" name="id" value="{{Post.id}}">
           <div><textarea id="comment-add-form" maxlength="250" name="text"></textarea></div>
           <div><input class="btn-send-comment" type="submit" value="Добавить комментарий"></div>
       </form>
       {% else %}
       <small>Для комментирования записей необходимо <a href="{% url 'login' %}?redirect={{request.build_absolute_uri|urlencode}}">авторизироваться</a></small>
       {% endif %}
       {% recursetree Post.comments.all %}
       <div class="comment" id="comment-{{node.id}}">
           <div class="comment-info">
               <span class="comment-author" id="comment-{{node.id}}-author"><a style="color:blue;" href="{% url 'user_profile' index=node.author.id %}">{{node.author|escape}}</a></span>
               <span class="comment-date" id="comment-{{node.id}}-date">{{node.pub_date}}</span>
           </div>
           <span class="comment-body">{{node.text|escape|bbcode}}</span>
           {% if node.get_ancestors.count < 4 %}<div><a class="btn-answer" href="#comment-add-form" onclick="answer('{{node.id}}','{{node.author}}','{{node.pub_date}}');"><small>Ответить</small></a></div>{% endif %}
           {% if not node.is_leaf_node %}
                <div class="comment-children">
                    {{ children }}
                </div>
            {% endif %}
       </div>
       {% endrecursetree %}
       {% if not Post.comments.all %}
           <span style="font-size: 15px;color: #708090;margin-left: 40%;margin-right: 40%;">Нет комментариев</span>
       {% endif %}
   </div>
{% endblock %}`

**Comment by ellmetha** [comment]
So your ``body`` / ``text`` fields are ``models.TextField`` instances or ``BBCodeTextField`` instances?

**Comment by ellmetha** [comment]
You could try to display your BBCodes as follows: ``{{ Post.body|safe|bbcode }}``

**Comment by Valeriy-Zainullin** [comment]
![2](https://cloud.githubusercontent.com/assets/16137770/12704206/92976c26-c866-11e5-9835-18f11344e966.png) Thanks. Works well. I think you should add this to docs (if it isn`t already there).

**Comment by ellmetha** [comment]
> Thanks. Works well. I think you should add this to docs (if it isn`t already there).

Yes. I will! ;)
